---

version: '3'

services:
  gvm-postgres:
    image: "reineltdev/postgres-gvm:11"
    hostname: "postgres-gvm"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres-socket:/var/run/postgresql"
      - "postgres-data:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_PASSWORD=gvm

  gvm-openvas:
    image: "reineltdev/openvas:20.8.0-1"
    hostname: "openvas"
    restart: always
    ports:
      - "51000:51234"
    volumes:
      - "gvm-connect:/usr/local/var/run"
      - "ospd-socket:/var/run/ospd"
      - "openvas-data:/usr/local/var/lib/openvas"
      - "gvm-data:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
    # environment:
    #   - COMMUNITY_NVT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/nvt-feed # Custom feed server https://github.com/reineltdev/gvm-feed-server
    #   - COMMUNITY_SCAP_RSYNC_FEED=rsync://gvm_feed_server.service.com:/scap-data # Custom feed server https://github.com/reineltdev/gvm-feed-server
    #   - COMMUNITY_GVMD_DATA_RSYNC_FEED=rsync://gvm_feed_server.service.com:/data-objects/gvmd/ # Custom feed server https://github.com/reineltdev/gvm-feed-server
    #   - COMMUNITY_CERT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/cert-data # Custom feed server https://github.com/reineltdev/gvm-feed-server

  gvm-gvmd:
    image: "reineltdev/gvmd:20.8.0-1"
    hostname: "gvmd"
    restart: always
    ports:
      - "9390:9390"
    volumes:
      - "gvm-connect:/usr/local/var/run"
      - "ospd-socket:/var/run/ospd"
      - "openvas-data:/usr/local/var/lib/openvas"
      - "gvm-data:/usr/local/var/lib/gvm"
      # - "/tmp/ssmtp=/etc/ssmtp" # optional - ssmtp config path
      - "postgres-socket:/var/run/postgresql"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - gvm-openvas
    depends_on:
      - gvm-openvas
      - gvm-postgres
    # environment:
    #   - COMMUNITY_NVT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/nvt-feed # Custom feed server https://github.com/reineltdev/gvm-feed-server
    #   - COMMUNITY_SCAP_RSYNC_FEED=rsync://gvm_feed_server.service.com:/scap-data # Custom feed server https://github.com/reineltdev/gvm-feed-server
    #   - COMMUNITY_GVMD_DATA_RSYNC_FEED=rsync://gvm_feed_server.service.com:/data-objects/gvmd/ # Custom feed server https://github.com/reineltdev/gvm-feed-server
    #   - COMMUNITY_CERT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/cert-data # Custom feed server https://github.com/reineltdev/gvm-feed-server

  gvm-gsa:
    image: "reineltdev/gsa:20.8.0"
    hostname: "gsa"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "gvm-data:/usr/local/var/lib/gvm"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - gvm-gvmd
    depends_on:
      - gvm-gvmd
    environment:
      - GVMD_ADDRESS=gvm-gvmd
      - GVMD_PORT=9390
      - ENABLE_CRON=false

volumes:
  gvm-connect:
  gvm-data:
  openvas-data:
  ospd-socket:
  postgres-socket:
  postgres-data:
